### ISSUE TITLE
Problem building NIQA

### ISSUE THREAD

**Issue by paandre2** [neutronimaging/imagingsuite#571]
Hello,

I am trying to build NIQA on Ubuntu 22 but I am experiencing issues.
I tried using both the script in  imagingsuite/build, and the script in the dedicated ImagingQuality repos. 
If I use the script in imagingsuite, an error occurs saying that the file 'tnt.h' is not found. Building ImagingQuality returns:

error: ‘AddLogTarget’ is not a member of ‘kipl::logging::Logger’

in the file niqamainwindow.cpp.
I have successfully (or so I think) executed the build_core_kipl, build_core_algorithms and build_core_modules scripts, before doing all that.

Thank you very much in advance for your help.

**Comment by paandre2** [comment]
Hello,

Thank you very much for your reply.
Using the cmake scripts work on imagingsuite, but then would it be possible (with some playing around) that I compile ImagingQuality?
If you give me the combination that is the mot likely to work, I can work around it.

**Comment by anderskaestner** [comment]
I fixed the build errors. It should work with cmake in imagingquality now. 
This is a fix based on the issue568_cleancmake branch of imaging suite.
The application will be located in the install/bin folder and for now you have to manually set the RPATH using 
``` chrpath -r ../lib:<Qt install path>/Qt/6.x.y/gcc_64/lib> NIQA```

Replace x and y by the version number for your installation of Qt.

**Comment by paandre2** [comment]
Hello,

Thank you very much for the change, now it builds (I had to manually link some libraries but maybe this is due to my installation).
I have now another issue when running the NIQA bin file:

qt.core.plugin.factoryloader: checking directory path "~/git/IQ-build/bin/platforms" ...
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""

Putting manually the libqxcb.so file in ~/git/IQ-build/bin/platforms gives another error:

Cannot load library /usr/lib/x86_64-linux-gnu/qt6/plugins/platforms/libqxcb.so: (/usr/lib/x86_64-linux-gnu/qt6/plugins/platforms/../../../libQt6XcbQpa.so.6: undefined symbol: _ZTIN16QNativeInterface15QX11ApplicationE, version Qt_6)

I am a bit lost wheter this is due to my installation of Qt, or to the installation of NIQA.

**Comment by anderskaestner** [comment]
Well, that is where I'm stuck in the development... the ```chrpath -r ...``` I mentioned above will bring you closer to a solution.

**Comment by paandre2** [comment]
Ah, I see.
Thank you for the explanation, at least it is good to know that I don't have to completely reinstall Qt. :)

**Comment by paandre2** [comment]
Dear Anders,
I still do not manage to run NIQA (even though there seems to be no problem during the building step), due to the "undefined symbol" error mentioned above.
From what I have read online, it looks important that I use the same version of Qt that was used for the development of NIQA. Do you mind telling me the version of Qt that you use? This way I can try to build imagingsuite and ImagingQuality again with this version.
Thank you very much in advance.

**Comment by anderskaestner** [comment]
I use Qt 6.2.?

A

On 9 Jan 2023, at 14:12, paandre2 ***@***.***> wrote:



Dear Anders,
I still do not manage to run NIQA (even though there seems to be no problem during the building step), due to the "undefined symbol" error mentioned above.
From what I have read online, it looks important that I use the same version of Qt that was used for the development of NIQA. Do you mind telling me the version of Qt that you use? This way I can try to build imagingsuite and ImagingQuality again with this version.
Thank you very much in advance.

**Comment by paandre2** [comment]
Hello,

I downgraded from Qt 6.4.2 to 6.2.4 and also used the online installer instead of the source installation.
Also, I had to execute build_core_algorithms.sh from imagingsuite in order to have the libImagingQAAlgorithms.so file, and had to use the ldd command on it for the building of NIQA to be complete. 
Now, everything works fine, I am just reporting all of this, in case it is needed by others.

Thanks a lot for your help with everything!
